export NUPLAN_MAP_VERSION="nuplan-maps-v1.0"
export NUPLAN_MAPS_ROOT="/data2/data/navsim/maps"
export NAVSIM_EXP_ROOT="/data2/data/navsim/exp"
export NAVSIM_DEVKIT_ROOT="/data1/cz/projects/navsim/navsim"
export OPENSCENE_DATA_ROOT="/data2/data/navsim"
